### ISSUE TITLE
"Trouble signing you in"

### ISSUE THREAD

**Issue by freerl** [microsoftgraph/msgraph-training-aspnetmvcapp#46]
I followed all the steps and I got the below message after signing in with my account.

"Sorry, but we’re having trouble signing you in. 
AADSTS700016: Application with identifier '{appID}' was not found in the directory '53fe2caa-607b-41c9-bdd6-cebd25cece19'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant. "

There are no instructions in the tutorial about consenting. I went to the applications API permissions and Azure and granted content for Microsoft Graph User.Read and Calendar.Read.
Are there other places to set consent? I am in Azure.gov.

**Comment by jasonjoh** [comment]
Consent happens during the first sign-in by the user. There's no need to consent to the permissions in the Azure portal, though it won't hurt anything if you do that.

The error you're getting is likely due to being in Azure.gov. You need to use different endpoints for authentication and for Graph, as detailed here: https://docs.microsoft.com/graph/deployments. I don't have any specific experience with this, but I think I can point you in the right direction.

- In Startup.Auth.cs, you need to updatethis line, replacing the `https://login.microsoftonline.com` with the applicable endpoint for you, and assuming you want only users in your tenant to sign in, you may want to replace `common` with your tenant ID.

```
Authority = "https://login.microsoftonline.com/common/v2.0",
```

For example, if you're on the US Gov Azure, you would update to:

```
Authority = "https://login.microsoftonline.us/53fe2caa-607b-41c9-bdd6-cebd25cece19/v2.0",
```

You're also going to want to use that same authority value when you initialize the ConfidentialClientApplication. The ConfidentialClientApplicationBuilder has a method called `WithAuthority` that can be added into the sample's code.

Finally, when you get to the part where you add the GraphServiceClient, you're going to want to pass a base URL in the constructor. So at this [step](https://docs.microsoft.com/en-us/graph/tutorials/aspnet?tutorial-step=3#get-user-details), use this code instead:

```
var graphClient = new GraphServiceClient(
    "https://graph.microsoft.us/",
    new DelegateAuthenticationProvider(
        async (requestMessage) =>
        {
            requestMessage.Headers.Authorization =
                new AuthenticationHeaderValue("Bearer", accessToken);
        }));
```

Let me know if that works for you.

**Comment by jasonjoh** [comment]
@freerl I just wanted to follow up and see if those changed worked for you. Let me know.
