### ISSUE TITLE
Cache Sign Out & Sign In Error

### ISSUE THREAD

**Issue by evillena-debug** [microsoftgraph/msgraph-training-aspnetmvcapp#50]
Apparently once the user session is closed, the token does not expire and lets you enter the application URL again without asking for the credentials, I believe that the cache remains heavy on the instruction.
The same thing happens in the video that I noticed;

https://youtu.be/a2teHZ5WuNc?t=2537  Min 42:17

**Comment by jasonjoh** [comment]
Yes the browser has your Microsoft identity already cached. The token isn't what's at play here, because the token's been thrown away, along with the MSAL cache. The app is actually going to the Microsoft identity platform (login.microsoftonline.com), which is then auto-signing the user in (typically because they ticked the "keep me signed in" box, or they're signed in to something else in another tab, etc.)

**Comment by evillena-debug** [comment]
Another question, how can I call the token from another controller as the method to obtain the calendar, in the example of the calendar it appears without parameters in the controller, therefore, it does not request access to the token. Unlike the GetUserDetails (string accessToken). Thanks for your help.

**Comment by evillena-debug** [comment]
I solved it
